name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Ejecutar este workflow al hacer push a la rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Clonar el repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # Loguearse en Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Construir y etiquetar la imagen Docker
    - name: Build and Tag Docker image
      run: |
        export TAG=$(date +'%Y%m%d-%H%M%S')
        echo "Using tag: $TAG"
        docker build -t elritosan/nginx-compilacionejerciciosp3:$TAG .
        docker tag elritosan/nginx-compilacionejerciciosp3:$TAG elritosan/nginx-compilacionejerciciosp3:latest
        echo "TAG=$TAG" >> $GITHUB_ENV

    # Publicar la imagen en Docker Hub
    - name: Push Docker image
      run: |
        docker push elritosan/nginx-compilacionejerciciosp3:${{ env.TAG }}
        docker push elritosan/nginx-compilacionejerciciosp3:latest
