name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Ejecutar este workflow al hacer push a la rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Clonar el repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # Loguearse en Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Construir y etiquetar la imagen Docker
    - name: Build and Tag Docker image
      run: |
        TAG=$(date +'%Y%m%d-%H%M%S')
        docker build -t elritosan/nginx-compilacionejerciciosp3:$TAG .
        docker tag elritosan/nginx-compilacionejerciciosp3:$TAG elritosan/nginx-compilacionejerciciosp3:latest

    # Publicar la imagen en Docker Hub
    - name: Push Docker image
      run: |
        TAG=$(date +'%Y%m%d-%H%M%S')
        docker push elritosan/nginx-compilacionejerciciosp3:$TAG
        docker push elritosan/nginx-compilacionejerciciosp3:latest
